api_root_path: /
auto_reload: true
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_name: metadata-store
db_url: mongodb://localhost:27017
docs_url: /docs
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
port: 8080
workers: 1

